version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"
  jobs:
    post_install:
      - pip install --upgrade pip
      - pip install --no-cache-dir kolmogorov-abacus
      - pip install --no-cache-dir -r requirements.txt

sphinx:
  builder: html
  configuration: docs/source/conf.py

python:
  install:
    - requirements: docs/requirements.txt

formats:
  - pdf
